_target_: torch.nn.Sequential
_args_:
- _target_: torch.nn.Conv2d
  in_channels: 3
  out_channels: 64
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.MaxPool2d
  kernel_size: 2
  stride: 2
- _target_: torch.nn.Conv2d
  in_channels: 64
  out_channels: 128
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.MaxPool2d
  kernel_size: 2
  stride: 2
- _target_: torch.nn.Conv2d
  in_channels: 128
  out_channels: 256
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.Conv2d
  in_channels: 256
  out_channels: 256
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.MaxPool2d
  kernel_size: 2
  stride: 2
- _target_: torch.nn.Conv2d
  in_channels: 256
  out_channels: 512
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.Conv2d
  in_channels: 512
  out_channels: 512
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.MaxPool2d
  kernel_size: 2
  stride: 2
- _target_: torch.nn.Conv2d
  in_channels: 512
  out_channels: 512
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
- _target_: torch.nn.Conv2d
  in_channels: 512
  out_channels: 512
  kernel_size: 3
  padding: 1
- _target_: torch.nn.ReLU
  inplace: true
