defaults: 
    #- data@data_train : cifar_compose
    - backbones@backbones.vgg : vgg8
    - train_config@training_steps.train : exponential_lr
    - data@training_steps.train.data_loader : cifar_compose
    - data@validation.data_loader : cifar_compose_test
    - _self_

hydra:
  run:
    dir: outputs/${comment}/${now:%Y-%m-%d_%H-%M-%S}/

heads:
  classifier_cifar10:
    _target_ : head.Projection
    _args_ :
      - 512
      - 10
  classifier_cifar100:
    _target_ : head.Projection
    _args_ :
      - 512
      - 100

losses:
  loss_cifar10:
    _target_ : head.WrappedLossFunction
    _args_ :
      - _target_ : torch.nn.CrossEntropyLoss
  loss_cifar100:
    _target_ : head.WrappedLossFunction
    _args_ :
      - _target_ : torch.nn.CrossEntropyLoss

metrics:
  accuracy_cifar100:
    _target_ : torchmetrics.classification.MulticlassAccuracy
    num_classes : 100
  accuracy_cifar10:
    _target_ : torchmetrics.classification.MulticlassAccuracy
    num_classes : 10

training_steps:
  train :
    epoch : 10
    inputs_handler :
       _target_ : meta_prog.MultidatasetInputManager
    graph :
      - input : CIFAR10
        node : vgg
        output_name : repr_cifar10
      - input : CIFAR100
        node : vgg
        output_name : repr_cifar100
      - input : repr_cifar10
        node : classifier_cifar10
        output_name : proj_cifar10
      - input : repr_cifar100
        node : classifier_cifar100
        output_name : proj_cifar100
      - input : proj_cifar10
        node : loss_cifar10
        output_name : loss_cifar10
      - input : proj_cifar100
        node : loss_cifar100
        output_name : loss_cifar100
      - input : proj_cifar10
        node : accuracy_cifar10
        output_name : accuracy_cifar10
      - input : proj_cifar100
        node : accuracy_cifar100
        output_name : accuracy_cifar100
validation :
  inputs_handler :
    _target_ : meta_prog.MultidatasetInputManager
  graph :
    - input : CIFAR10
      node : vgg
      output_name : repr_cifar10
    - input : CIFAR100
      node : vgg
      output_name : repr_cifar100
    - input : repr_cifar10
      node : classifier_cifar10
      output_name : proj_cifar10
    - input : repr_cifar100
      node : classifier_cifar100
      output_name : proj_cifar100
    - input : proj_cifar10
      node : loss_cifar10
      output_name : loss_cifar10
    - input : proj_cifar100
      node : loss_cifar100
      output_name : loss_cifar100
    - input : proj_cifar10
      node : accuracy_cifar10
      output_name : accuracy_cifar10
    - input : proj_cifar100
      node : accuracy_cifar100
      output_name : accuracy_cifar100
comment : "vgg8 + cifar10 & cifar100"